// next-app/src/components/Footer.tsx
import React from 'react';
import { Link } from '../lib/router-compat';
import { 
  Calculator, 
  ArrowUp,
  Mail,
  Github,
  Twitter,
  Linkedin
} from 'lucide-react';
import EEATFooter from './EEATFooter';

export const Footer: React.FC = () => {
  const scrollToTop = () => {
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  /** Hub-only links – crawl budget control, clean authority funnels (SEO). */
  const footerSections = [
    {
      title: 'Tools & Calculators',
      links: [
        { name: 'Calculators', href: '/calculators' },
        { name: 'Finance Tools', href: '/finance-tools' },
        { name: 'Tax Tools', href: '/tax-tools' },
        { name: 'GST Tools', href: '/gst-tools' },
        { name: 'Insurance Tools', href: '/insurance-tools' },
        { name: 'Tools', href: '/tools' },
      ]
    },
    {
      title: 'Resources',
      links: [
        { name: 'Learn', href: '/learn' },
        { name: 'Blog', href: '/blog' },
        { name: 'News', href: '/news' },
        { name: 'Government Schemes', href: '/government-schemes' },
        { name: 'Crypto', href: '/crypto' },
      ]
    },
    {
      title: 'Company',
      links: [
        { name: 'About Us', href: '/about-us' },
        { name: 'Contact', href: '/contact-us' },
        { name: 'Privacy Policy', href: '/privacy-policy' },
        { name: 'Terms of Use', href: '/terms-of-use' },
        { name: 'Disclaimer', href: '/disclaimer' },
        { name: 'Cookie Policy', href: '/cookie-policy' },
      ]
    }
  ];

  const socialLinks = [
    { name: 'Twitter', icon: Twitter, href: 'https://twitter.com/MoneyCalIN' },
    { name: 'LinkedIn', icon: Linkedin, href: 'https://linkedin.com/company/moneycal' },
    { name: 'GitHub', icon: Github, href: 'https://github.com/harshraj0235/fincal' },
  ];

  return (
    <footer className="bg-white border-t border-gray-200">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        {/* Main Footer Content */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-8 mb-8">
          {/* Brand Section */}
          <div className="col-span-2 md:col-span-1">
            <Link to="/" className="flex items-center space-x-2 mb-4">
              <div className="w-10 h-10 bg-blue-600 rounded-lg flex items-center justify-center">
                <Calculator className="w-6 h-6 text-white" />
              </div>
              <h3 className="text-xl font-semibold text-gray-900">
                MoneyCal.in
              </h3>
            </Link>
            <p className="text-gray-600 text-sm leading-relaxed mb-4">
              India's most comprehensive financial calculator platform. Free tools for loans, investments, taxes, and more.
            </p>
            <div className="flex items-center space-x-2 text-sm text-gray-600">
              <Mail className="w-4 h-4" />
              <a href="mailto:support@moneycal.in" className="hover:text-blue-600">
                support@moneycal.in
              </a>
            </div>
          </div>
          
          {/* Footer Sections */}
          {footerSections.map((section) => (
            <div key={section.title}>
              <h4 className="text-sm font-semibold text-gray-900 mb-4">
                {section.title}
              </h4>
              <ul className="space-y-3">
                {section.links.map((link) => (
                  <li key={link.name}>
                    <Link
                      to={link.href}
                      className="text-sm text-gray-600 hover:text-blue-600 transition-colors"
                    >
                      {link.name}
                    </Link>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>

        {/* E-E-A-T: Experience, Expertise, Authoritativeness, Trust (Google quality) */}
        <EEATFooter />

        {/* Bottom Bar */}
        <div className="border-t border-gray-200 pt-8">
          <div className="flex flex-col md:flex-row justify-between items-center space-y-4 md:space-y-0">
            {/* Copyright */}
            <div className="text-sm text-gray-600">
              © {new Date().getFullYear()} MoneyCal.in. All rights reserved.
            </div>

            {/* Social Links */}
            <div className="flex items-center space-x-4">
              {socialLinks.map((social) => {
                const Icon = social.icon;
                return (
                  <a
                    key={social.name}
                    href={social.href}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-gray-400 hover:text-gray-600 transition-colors"
                    aria-label={social.name}
                  >
                    <Icon className="w-5 h-5" />
                  </a>
                );
              })}
            </div>

            {/* Back to Top */}
            <button
              onClick={scrollToTop}
              className="flex items-center space-x-2 text-sm text-gray-600 hover:text-blue-600 transition-colors"
              aria-label="Back to top"
            >
              <span>Back to top</span>
              <ArrowUp className="w-4 h-4" />
            </button>
          </div>
        </div>
      </div>
    </footer>
  );
};

// src/lib/components/Footer.svelte
<script lang="ts">
  const footerSections = [
    {
      title: 'Tools & Calculators',
      links: [
        { href: '/', label: 'Home' },
        { href: '/calculators', label: 'Calculators' },
        { href: '/tools', label: 'All Tools' },
        { href: '/tax-tools', label: 'Tax Tools' },
        { href: '/gst-tools', label: 'GST Tools' },
        { href: '/gold-tools', label: 'Gold Tools' },
        { href: '/loan-tools', label: 'Loan Tools' },
        { href: '/insurance-tools', label: 'Insurance Tools' },
      ],
    },
    {
      title: 'Learn & News',
      links: [
        { href: '/learn', label: 'Learn' },
        { href: '/blog', label: 'Blog' },
        { href: '/news', label: 'News' },
        { href: '/news/shorts', label: 'Money Shorts' },
        { href: '/government-schemes', label: 'Govt Schemes' },
        { href: '/crypto', label: 'Crypto' },
      ],
    },
    {
      title: 'Company',
      links: [
        { href: '/about-us', label: 'About Us' },
        { href: '/contact-us', label: 'Contact' },
        { href: '/privacy-policy', label: 'Privacy Policy' },
        { href: '/terms-of-service', label: 'Terms of Service' },
        { href: '/disclaimer', label: 'Disclaimer' },
      ],
    },
  ];
</script>

<footer class="site-footer" role="contentinfo">
  <div class="footer-inner">
    <div class="footer-brand">
      <a href="/" class="footer-logo">MoneyCal.in</a>
      <p class="footer-tagline">Free financial calculators & tools for India. Tax, Gold, GST, Loans & more.</p>
    </div>
    <div class="footer-grid">
      {#each footerSections as section}
        <div class="footer-col">
          <h3 class="footer-title">{section.title}</h3>
          <ul class="footer-links">
            {#each section.links as link}
              <li>
                <a href={link.href} class="footer-link">{link.label}</a>
              </li>
            {/each}
          </ul>
        </div>
      {/each}
    </div>
    <div class="footer-bottom">
      <p>© {new Date().getFullYear()} MoneyCal.in. All tools free. No sign-up required.</p>
    </div>
  </div>
</footer>

<style>
  .site-footer {
    background: linear-gradient(180deg, #f8fafc, #f1f5f9);
    border-top: 1px solid #e2e8f0;
    padding: 2.5rem 1rem 1.5rem;
    margin-top: auto;
  }
  .footer-inner {
    max-width: 80rem;
    margin: 0 auto;
  }
  .footer-brand {
    margin-bottom: 2rem;
  }
  .footer-logo {
    display: inline-block;
    font-weight: 800;
    font-size: 1.25rem;
    color: #0f172a;
    text-decoration: none;
    margin-bottom: 0.5rem;
  }
  .footer-logo:hover {
    color: #2563eb;
  }
  .footer-tagline {
    font-size: 0.875rem;
    color: #64748b;
    max-width: 28rem;
    margin: 0;
  }
  .footer-grid {
    display: grid;
    gap: 2rem;
    grid-template-columns: 1fr;
  }
  @media (min-width: 640px) {
    .footer-grid {
      grid-template-columns: repeat(2, 1fr);
    }
  }
  @media (min-width: 1024px) {
    .footer-grid {
      grid-template-columns: repeat(3, 1fr);
    }
  }
  .footer-title {
    font-size: 0.875rem;
    font-weight: 700;
    color: #0f172a;
    margin: 0 0 0.75rem 0;
    text-transform: uppercase;
    letter-spacing: 0.05em;
  }
  .footer-links {
    list-style: none;
    margin: 0;
    padding: 0;
  }
  .footer-links li {
    margin-bottom: 0.5rem;
  }
  .footer-link {
    display: inline-block;
    padding: 0.25rem 0;
    padding: 0.35rem 0;
    font-size: 0.9375rem;
    color: #475569;
    text-decoration: none;
  }
  .footer-link:hover {
    color: #2563eb;
    text-decoration: underline;
  }
  .footer-bottom {
    margin-top: 2.5rem;
    padding-top: 1.5rem;
    border-top: 1px solid #e2e8f0;
    text-align: center;
  }
  .footer-bottom p {
    font-size: 0.875rem;
    color: #64748b;
    margin: 0;
  }
</style>
